apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
    repoURL: 'https://github.com/tokyo2006/service-config-repo.git'
    revision: HEAD
    directories:
    - path: 'services/guest-book/**/config.json'
  template:
    metadata:
      name: 'sandbox-cn-guestbook'
    spec:
      project: stack
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
      source:
        repoURL: 'https://github.com/tokyo2006/{{ .helm_repo }}.git'
        targetRevision: HEAD
        path: {{ .helm_path}}
        helm:
          valueFiles:
          - '{{ .values_path }}/sandbox-cn/guest-book.yaml'
          releaseName: 'guestbook'
          valuesObject:
            image:
              repository: 120867251111.dkr.ecr.cn-northwest-1.amazonaws.com.cn/tradeshift-base/ks-guestbook-demo
              tag: {{ .image_tag }}
            annotations:
              team: platform-ops
              repository: https://github.com/Tradeshift/argocd-example-apps
            resources:
              requests:
                cpu: 100m
                memory: 100Mi
              limits:
                cpu: 100m
                memory: 100Mi
            affinity:
              podAntiAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                    - key: app
                      operator: In
                      values:
                      - guestbook
                  topologyKey: kubernetes.io/hostname
      destination:
        server: '{{.cluster_server}}'
        namespace: 'default'
